.TH "G:/Libraries/VSProjects/UntitledEngine/Engine-Core/src/maths Directory Reference" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/Libraries/VSProjects/UntitledEngine/Engine-Core/src/maths Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmaths\&.h\fP"
.br
.ti -1c
.RI "file \fBvec2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvec2\&.h\fP"
.br
.ti -1c
.RI "file \fBvec3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvec3\&.h\fP"
.br
.ti -1c
.RI "file \fBvec4\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvec4\&.h\fP"
.br
.in -1c
