.TH "GLFWimage" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWimage \- Image data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "unsigned char * \fBpixels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Image data\&. 
.PP
Definition at line 1031 of file glfw3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLFWimage::height"
The height, in pixels, of this image\&. 
.PP
Definition at line 1038 of file glfw3\&.h\&.
.SS "unsigned char* GLFWimage::pixels"
The pixel data of this image, arranged left-to-right, top-to-bottom\&. 
.PP
Definition at line 1041 of file glfw3\&.h\&.
.SS "\fBint\fP GLFWimage::width"
The width, in pixels, of this image\&. 
.PP
Definition at line 1035 of file glfw3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
