.TH "GLFWgammaramp" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWgammaramp \- Gamma ramp\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short * \fBred\fP"
.br
.ti -1c
.RI "unsigned short * \fBgreen\fP"
.br
.ti -1c
.RI "unsigned short * \fBblue\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamma ramp\&. 

This describes the gamma ramp for a monitor\&.
.PP
\fBSee also:\fP
.RS 4
\fBglfwGetGammaRamp\fP \fBglfwSetGammaRamp\fP 
.RE
.PP

.PP
Definition at line 1013 of file glfw3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned short* GLFWgammaramp::blue"
An array of value describing the response of the blue channel\&. 
.PP
Definition at line 1023 of file glfw3\&.h\&.
.SS "unsigned short* GLFWgammaramp::green"
An array of value describing the response of the green channel\&. 
.PP
Definition at line 1020 of file glfw3\&.h\&.
.SS "unsigned short* GLFWgammaramp::red"
An array of value describing the response of the red channel\&. 
.PP
Definition at line 1017 of file glfw3\&.h\&.
.SS "unsigned \fBint\fP GLFWgammaramp::size"
The number of elements in each array\&. 
.PP
Definition at line 1026 of file glfw3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
