.TH "GLXPipeRect" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRect \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBsrcXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1267 of file glxew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLXPipeRect::destHeight"

.PP
Definition at line 1276 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::destWidth"

.PP
Definition at line 1275 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::destXOrigin"

.PP
Definition at line 1273 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::destYOrigin"

.PP
Definition at line 1274 of file glxew\&.h\&.
.SS "char GLXPipeRect::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Definition at line 1268 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcHeight"

.PP
Definition at line 1272 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcWidth"

.PP
Definition at line 1271 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcXOrigin"

.PP
Definition at line 1269 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcYOrigin"

.PP
Definition at line 1270 of file glxew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
