.TH "GLXPipeRectLimits" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRectLimits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxWidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1254 of file glxew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLXPipeRectLimits::maxHeight"

.PP
Definition at line 1258 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::maxWidth"

.PP
Definition at line 1259 of file glxew\&.h\&.
.SS "char GLXPipeRectLimits::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Definition at line 1255 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::XOrigin"

.PP
Definition at line 1256 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::YOrigin"

.PP
Definition at line 1257 of file glxew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
