.TH "G:/Libraries/VSProjects/UntitledEngine/Engine-Core/main.cpp" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/Libraries/VSProjects/UntitledEngine/Engine-Core/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'src\\graphics\\window\&.h'\fP
.br
\fC#include 'src\\maths\\maths\&.h'\fP
.br
\fC#include <glfw3\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main ()"

.PP
Definition at line 5 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
