.TH "shapes" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shapes \- Standard cursor shapes
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_ARROW_CURSOR\fP   0x00036001"
.br
.RI "\fIThe regular arrow cursor shape\&. \fP"
.ti -1c
.RI "#define \fBGLFW_IBEAM_CURSOR\fP   0x00036002"
.br
.RI "\fIThe text input I-beam cursor shape\&. \fP"
.ti -1c
.RI "#define \fBGLFW_CROSSHAIR_CURSOR\fP   0x00036003"
.br
.RI "\fIThe crosshair shape\&. \fP"
.ti -1c
.RI "#define \fBGLFW_HAND_CURSOR\fP   0x00036004"
.br
.RI "\fIThe hand shape\&. \fP"
.ti -1c
.RI "#define \fBGLFW_HRESIZE_CURSOR\fP   0x00036005"
.br
.RI "\fIThe horizontal resize arrow shape\&. \fP"
.ti -1c
.RI "#define \fBGLFW_VRESIZE_CURSOR\fP   0x00036006"
.br
.RI "\fIThe vertical resize arrow shape\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
See \fBstandard cursor creation\fP for how these are used\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_ARROW_CURSOR   0x00036001"

.PP
The regular arrow cursor shape\&. The regular arrow cursor\&. 
.PP
Definition at line 661 of file glfw3\&.h\&.
.SS "#define GLFW_CROSSHAIR_CURSOR   0x00036003"

.PP
The crosshair shape\&. The crosshair shape\&. 
.PP
Definition at line 671 of file glfw3\&.h\&.
.SS "#define GLFW_HAND_CURSOR   0x00036004"

.PP
The hand shape\&. The hand shape\&. 
.PP
Definition at line 676 of file glfw3\&.h\&.
.SS "#define GLFW_HRESIZE_CURSOR   0x00036005"

.PP
The horizontal resize arrow shape\&. The horizontal resize arrow shape\&. 
.PP
Definition at line 681 of file glfw3\&.h\&.
.SS "#define GLFW_IBEAM_CURSOR   0x00036002"

.PP
The text input I-beam cursor shape\&. The text input I-beam cursor shape\&. 
.PP
Definition at line 666 of file glfw3\&.h\&.
.SS "#define GLFW_VRESIZE_CURSOR   0x00036006"

.PP
The vertical resize arrow shape\&. The vertical resize arrow shape\&. 
.PP
Definition at line 686 of file glfw3\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
