.TH "u_engine::maths::vec3" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_engine::maths::vec3 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vec3\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvec3\fP ()"
.br
.ti -1c
.RI "\fBvec3\fP (const float &\fBx\fP, const float &\fBy\fP, const float &\fBz\fP)"
.br
.ti -1c
.RI "\fBvec3\fP & \fBadd\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "\fBvec3\fP & \fBsubstract\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "\fBvec3\fP & \fBmultiply\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "\fBvec3\fP & \fBdivide\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "\fBvec3\fP & \fBoperator+=\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "\fBvec3\fP & \fBoperator\-=\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "\fBvec3\fP & \fBoperator*=\fP (const \fBvec3\fP &other)"
.br
.ti -1c
.RI "\fBvec3\fP & \fBoperator/=\fP (const \fBvec3\fP &other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBvec3\fP \fBoperator+\fP (\fBvec3\fP \fBleft\fP, const \fBvec3\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec3\fP \fBoperator\-\fP (\fBvec3\fP \fBleft\fP, const \fBvec3\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec3\fP \fBoperator*\fP (\fBvec3\fP \fBleft\fP, const \fBvec3\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec3\fP \fBoperator/\fP (\fBvec3\fP \fBleft\fP, const \fBvec3\fP &\fBright\fP)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &\fBstream\fP, const \fBvec3\fP &vector)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file vec3\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "u_engine::maths::vec3::vec3 ()"

.PP
Definition at line 5 of file vec3\&.cpp\&.
.SS "u_engine::maths::vec3::vec3 (const float & x, const float & y, const float & z)"

.PP
Definition at line 11 of file vec3\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvec3\fP & u_engine::maths::vec3::add (const \fBvec3\fP & other)"

.PP
Definition at line 18 of file vec3\&.cpp\&.
.SS "\fBvec3\fP & u_engine::maths::vec3::divide (const \fBvec3\fP & other)"

.PP
Definition at line 39 of file vec3\&.cpp\&.
.SS "\fBvec3\fP & u_engine::maths::vec3::multiply (const \fBvec3\fP & other)"

.PP
Definition at line 32 of file vec3\&.cpp\&.
.SS "bool u_engine::maths::vec3::operator!= (const \fBvec3\fP & other)"

.PP
Definition at line 84 of file vec3\&.cpp\&.
.SS "\fBvec3\fP & u_engine::maths::vec3::operator*= (const \fBvec3\fP & other)"

.PP
Definition at line 70 of file vec3\&.cpp\&.
.SS "\fBvec3\fP & u_engine::maths::vec3::operator+= (const \fBvec3\fP & other)"

.PP
Definition at line 62 of file vec3\&.cpp\&.
.SS "\fBvec3\fP & u_engine::maths::vec3::operator\-= (const \fBvec3\fP & other)"

.PP
Definition at line 66 of file vec3\&.cpp\&.
.SS "\fBvec3\fP & u_engine::maths::vec3::operator/= (const \fBvec3\fP & other)"

.PP
Definition at line 74 of file vec3\&.cpp\&.
.SS "bool u_engine::maths::vec3::operator== (const \fBvec3\fP & other)"

.PP
Definition at line 80 of file vec3\&.cpp\&.
.SS "\fBvec3\fP & u_engine::maths::vec3::substract (const \fBvec3\fP & other)"

.PP
Definition at line 25 of file vec3\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBvec3\fP operator* (\fBvec3\fP left, const \fBvec3\fP & right)\fC [friend]\fP"

.PP
Definition at line 53 of file vec3\&.cpp\&.
.SS "\fBvec3\fP operator+ (\fBvec3\fP left, const \fBvec3\fP & right)\fC [friend]\fP"

.PP
Definition at line 47 of file vec3\&.cpp\&.
.SS "\fBvec3\fP operator\- (\fBvec3\fP left, const \fBvec3\fP & right)\fC [friend]\fP"

.PP
Definition at line 50 of file vec3\&.cpp\&.
.SS "\fBvec3\fP operator/ (\fBvec3\fP left, const \fBvec3\fP & right)\fC [friend]\fP"

.PP
Definition at line 56 of file vec3\&.cpp\&.
.SS "std::ostream& operator<< (std::ostream & stream, const \fBvec3\fP & vector)\fC [friend]\fP"

.PP
Definition at line 89 of file vec3\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "float u_engine::maths::vec3::x"

.PP
Definition at line 6 of file vec3\&.h\&.
.SS "float u_engine::maths::vec3::y"

.PP
Definition at line 6 of file vec3\&.h\&.
.SS "float u_engine::maths::vec3::z"

.PP
Definition at line 6 of file vec3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
