.TH "u_engine::maths" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_engine::maths \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvec2\fP"
.br
.ti -1c
.RI "struct \fBvec3\fP"
.br
.ti -1c
.RI "struct \fBvec4\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvec2\fP \fBoperator+\fP (\fBvec2\fP \fBleft\fP, const \fBvec2\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec2\fP \fBoperator\-\fP (\fBvec2\fP \fBleft\fP, const \fBvec2\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec2\fP \fBoperator*\fP (\fBvec2\fP \fBleft\fP, const \fBvec2\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec2\fP \fBoperator/\fP (\fBvec2\fP \fBleft\fP, const \fBvec2\fP &\fBright\fP)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &\fBstream\fP, const \fBvec2\fP &vector)"
.br
.ti -1c
.RI "\fBvec3\fP \fBoperator+\fP (\fBvec3\fP \fBleft\fP, const \fBvec3\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec3\fP \fBoperator\-\fP (\fBvec3\fP \fBleft\fP, const \fBvec3\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec3\fP \fBoperator*\fP (\fBvec3\fP \fBleft\fP, const \fBvec3\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec3\fP \fBoperator/\fP (\fBvec3\fP \fBleft\fP, const \fBvec3\fP &\fBright\fP)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &\fBstream\fP, const \fBvec3\fP &vector)"
.br
.ti -1c
.RI "\fBvec4\fP \fBoperator+\fP (\fBvec4\fP \fBleft\fP, const \fBvec4\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec4\fP \fBoperator\-\fP (\fBvec4\fP \fBleft\fP, const \fBvec4\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec4\fP \fBoperator*\fP (\fBvec4\fP \fBleft\fP, const \fBvec4\fP &\fBright\fP)"
.br
.ti -1c
.RI "\fBvec4\fP \fBoperator/\fP (\fBvec4\fP \fBleft\fP, const \fBvec4\fP &\fBright\fP)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &\fBstream\fP, const \fBvec4\fP &vector)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvec2\fP u_engine::maths::operator* (\fBvec2\fP left, const \fBvec2\fP & right)"

.PP
Definition at line 51 of file vec2\&.cpp\&.
.SS "\fBvec3\fP u_engine::maths::operator* (\fBvec3\fP left, const \fBvec3\fP & right)"

.PP
Definition at line 53 of file vec3\&.cpp\&.
.SS "\fBvec4\fP u_engine::maths::operator* (\fBvec4\fP left, const \fBvec4\fP & right)"

.PP
Definition at line 61 of file vec4\&.cpp\&.
.SS "\fBvec2\fP u_engine::maths::operator+ (\fBvec2\fP left, const \fBvec2\fP & right)"

.PP
Definition at line 45 of file vec2\&.cpp\&.
.SS "\fBvec3\fP u_engine::maths::operator+ (\fBvec3\fP left, const \fBvec3\fP & right)"

.PP
Definition at line 47 of file vec3\&.cpp\&.
.SS "\fBvec4\fP u_engine::maths::operator+ (\fBvec4\fP left, const \fBvec4\fP & right)"

.PP
Definition at line 55 of file vec4\&.cpp\&.
.SS "\fBvec2\fP u_engine::maths::operator\- (\fBvec2\fP left, const \fBvec2\fP & right)"

.PP
Definition at line 48 of file vec2\&.cpp\&.
.SS "\fBvec3\fP u_engine::maths::operator\- (\fBvec3\fP left, const \fBvec3\fP & right)"

.PP
Definition at line 50 of file vec3\&.cpp\&.
.SS "\fBvec4\fP u_engine::maths::operator\- (\fBvec4\fP left, const \fBvec4\fP & right)"

.PP
Definition at line 58 of file vec4\&.cpp\&.
.SS "\fBvec2\fP u_engine::maths::operator/ (\fBvec2\fP left, const \fBvec2\fP & right)"

.PP
Definition at line 54 of file vec2\&.cpp\&.
.SS "\fBvec3\fP u_engine::maths::operator/ (\fBvec3\fP left, const \fBvec3\fP & right)"

.PP
Definition at line 56 of file vec3\&.cpp\&.
.SS "\fBvec4\fP u_engine::maths::operator/ (\fBvec4\fP left, const \fBvec4\fP & right)"

.PP
Definition at line 64 of file vec4\&.cpp\&.
.SS "std::ostream& u_engine::maths::operator<< (std::ostream & stream, const \fBvec2\fP & vector)"

.PP
Definition at line 87 of file vec2\&.cpp\&.
.SS "std::ostream& u_engine::maths::operator<< (std::ostream & stream, const \fBvec3\fP & vector)"

.PP
Definition at line 89 of file vec3\&.cpp\&.
.SS "std::ostream& u_engine::maths::operator<< (std::ostream & stream, const \fBvec4\fP & vector)"

.PP
Definition at line 97 of file vec4\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
