.TH "u_engine::graphics" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_engine::graphics \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBwindow_resize\fP (\fBGLFWwindow\fP *window, \fBint\fP \fBwidth\fP, \fBint\fP \fBheight\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmouse_button_callback\fP (\fBGLFWwindow\fP *window, \fBint\fP button, \fBint\fP action, \fBint\fP mods)"
.br
.ti -1c
.RI "\fBvoid\fP \fBkey_callback\fP (\fBGLFWwindow\fP *window, \fBint\fP key, \fBint\fP scancode, \fBint\fP action, \fBint\fP mods)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcursor_position_callback\fP (\fBGLFWwindow\fP *window, double xpos, double ypos)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP u_engine::graphics::cursor_position_callback (\fBGLFWwindow\fP * window, double xpos, double ypos)"

.PP
Definition at line 125 of file window\&.cpp\&.
.SS "\fBvoid\fP u_engine::graphics::key_callback (\fBGLFWwindow\fP * window, \fBint\fP key, \fBint\fP scancode, \fBint\fP action, \fBint\fP mods)"

.PP
Definition at line 120 of file window\&.cpp\&.
.SS "\fBvoid\fP u_engine::graphics::mouse_button_callback (\fBGLFWwindow\fP * window, \fBint\fP button, \fBint\fP action, \fBint\fP mods)"

.PP
Definition at line 115 of file window\&.cpp\&.
.SS "\fBvoid\fP u_engine::graphics::window_resize (\fBGLFWwindow\fP * window, \fBint\fP width, \fBint\fP height)"

.PP
Definition at line 110 of file window\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
