.TH "u_engine::graphics::Window" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u_engine::graphics::Window \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP (const char *title, \fBint\fP \fBwidth\fP, \fBint\fP \fBheight\fP)"
.br
.ti -1c
.RI "\fB~Window\fP ()"
.br
.ti -1c
.RI "bool \fBclosed\fP () const "
.br
.ti -1c
.RI "\fBvoid\fP \fBupdate\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBclear\fP () const "
.br
.ti -1c
.RI "\fBint\fP \fBgetWidth\fP () const "
.br
.ti -1c
.RI "\fBint\fP \fBgetHeight\fP () const "
.br
.ti -1c
.RI "bool \fBisKeyPressed\fP (unsigned \fBint\fP keycode) const "
.br
.ti -1c
.RI "bool \fBisMButtonPressed\fP (unsigned \fBint\fP button) const "
.br
.ti -1c
.RI "\fBvoid\fP \fBgetMousePosition\fP (double &\fBx\fP, double &\fBy\fP) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBGLFWwindow\fP"
.br
.RI "\fIOpaque window object\&. \fP"
.ti -1c
.RI "static friend \fBvoid\fP \fBmouse_button_callback\fP (\fBGLFWwindow\fP *window, \fBint\fP button, \fBint\fP action, \fBint\fP mods)"
.br
.ti -1c
.RI "static friend \fBvoid\fP \fBkey_callback\fP (\fBGLFWwindow\fP *window, \fBint\fP key, \fBint\fP scancode, \fBint\fP action, \fBint\fP mods)"
.br
.ti -1c
.RI "static friend \fBvoid\fP \fBcursor_position_callback\fP (\fBGLFWwindow\fP *window, double xpos, double ypos)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file window\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "u_engine::graphics::Window::Window (const char * title, \fBint\fP width, \fBint\fP height)"

.PP
Definition at line 12 of file window\&.cpp\&.
.SS "u_engine::graphics::Window::~Window ()"

.PP
Definition at line 33 of file window\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP u_engine::graphics::Window::clear () const"

.PP
Definition at line 96 of file window\&.cpp\&.
.SS "bool u_engine::graphics::Window::closed () const"

.PP
Definition at line 105 of file window\&.cpp\&.
.SS "\fBint\fP u_engine::graphics::Window::getHeight () const\fC [inline]\fP"

.PP
Definition at line 32 of file window\&.h\&.
.SS "\fBvoid\fP u_engine::graphics::Window::getMousePosition (double & x, double & y) const"

.PP
Definition at line 91 of file window\&.cpp\&.
.SS "\fBint\fP u_engine::graphics::Window::getWidth () const\fC [inline]\fP"

.PP
Definition at line 31 of file window\&.h\&.
.SS "bool u_engine::graphics::Window::isKeyPressed (unsigned \fBint\fP keycode) const"

.PP
Definition at line 73 of file window\&.cpp\&.
.SS "bool u_engine::graphics::Window::isMButtonPressed (unsigned \fBint\fP button) const"

.PP
Definition at line 82 of file window\&.cpp\&.
.SS "\fBvoid\fP u_engine::graphics::Window::update ()"

.PP
Definition at line 100 of file window\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "static friend \fBvoid\fP cursor_position_callback (\fBGLFWwindow\fP * window, double xpos, double ypos)\fC [friend]\fP"

.PP
Definition at line 125 of file window\&.cpp\&.
.SS "friend struct \fBGLFWwindow\fP\fC [friend]\fP"

.PP
Opaque window object\&. Opaque window object\&. 
.PP
Definition at line 13 of file window\&.h\&.
.SS "static friend \fBvoid\fP key_callback (\fBGLFWwindow\fP * window, \fBint\fP key, \fBint\fP scancode, \fBint\fP action, \fBint\fP mods)\fC [friend]\fP"

.PP
Definition at line 120 of file window\&.cpp\&.
.SS "static friend \fBvoid\fP mouse_button_callback (\fBGLFWwindow\fP * window, \fBint\fP button, \fBint\fP action, \fBint\fP mods)\fC [friend]\fP"

.PP
Definition at line 115 of file window\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
