.TH "G:/Libraries/VSProjects/UntitledEngine/Engine-Core/src/maths/vec3.cpp" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/Libraries/VSProjects/UntitledEngine/Engine-Core/src/maths/vec3.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'vec3\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBu_engine\fP"
.br
.ti -1c
.RI " \fBu_engine::maths\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "vec3 \fBu_engine::maths::operator+\fP (vec3 \fBleft\fP, const vec3 &\fBright\fP)"
.br
.ti -1c
.RI "vec3 \fBu_engine::maths::operator\-\fP (vec3 \fBleft\fP, const vec3 &\fBright\fP)"
.br
.ti -1c
.RI "vec3 \fBu_engine::maths::operator*\fP (vec3 \fBleft\fP, const vec3 &\fBright\fP)"
.br
.ti -1c
.RI "vec3 \fBu_engine::maths::operator/\fP (vec3 \fBleft\fP, const vec3 &\fBright\fP)"
.br
.ti -1c
.RI "std::ostream & \fBu_engine::maths::operator<<\fP (std::ostream &\fBstream\fP, const vec3 &vector)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
