.TH "G:/Libraries/VSProjects/UntitledEngine/Engine-Core/src/graphics/window.h" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/Libraries/VSProjects/UntitledEngine/Engine-Core/src/graphics/window.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <glew\&.h>\fP
.br
\fC#include <glfw3\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBu_engine::graphics::Window\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBu_engine\fP"
.br
.ti -1c
.RI " \fBu_engine::graphics\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_KEYS\fP   1024"
.br
.ti -1c
.RI "#define \fBMAX_BUTTONS\fP   32"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_BUTTONS   32"

.PP
Definition at line 9 of file window\&.h\&.
.SS "#define MAX_KEYS   1024"

.PP
Definition at line 8 of file window\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
