.TH "G:/Libraries/VSProjects/UntitledEngine/Engine-Core/src/graphics/window.cpp" 3 "Sun Aug 23 2015" "Version v0.0.3" "UntitledEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/Libraries/VSProjects/UntitledEngine/Engine-Core/src/graphics/window.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'window\&.h'\fP
.br
\fC#include <glew\&.h>\fP
.br
\fC#include <glfw3\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBu_engine\fP"
.br
.ti -1c
.RI " \fBu_engine::graphics\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBu_engine::graphics::window_resize\fP (\fBGLFWwindow\fP *window, \fBint\fP \fBwidth\fP, \fBint\fP \fBheight\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBu_engine::graphics::mouse_button_callback\fP (\fBGLFWwindow\fP *window, \fBint\fP button, \fBint\fP action, \fBint\fP mods)"
.br
.ti -1c
.RI "\fBvoid\fP \fBu_engine::graphics::key_callback\fP (\fBGLFWwindow\fP *window, \fBint\fP key, \fBint\fP scancode, \fBint\fP action, \fBint\fP mods)"
.br
.ti -1c
.RI "\fBvoid\fP \fBu_engine::graphics::cursor_position_callback\fP (\fBGLFWwindow\fP *window, double xpos, double ypos)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UntitledEngine from the source code\&.
